version: '3.8'

services:
  springboot-app:
    build: .
    container_name: wakefit-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-cvkff4t6ubrc73fo8c20-a.oregon-postgres.render.com:5432/wakefitdb
      SPRING_DATASOURCE_USERNAME: wakefit_user
      SPRING_DATASOURCE_PASSWORD: 2TNqBMrASMjEzzCMnHoKhZrLgH9B4Cjw
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    networks:
      - wakefit-net

networks:
  wakefit-net:
    driver: bridge
